[[redirects]]
    from = "/import/*"
    to="/.netlify/functions/import?script=:splat"
    status = 200
    force = true

[[redirects]]
    from = "/url-splat/:splat"
    to = "/.netlify/functions/url-splat?splat=:splat"
    status=200
    force = true

[build]
    publish = "public/"
    functions="functions/"
